(hall-description
  (name "ebbot")
  (prefix "")
  (version "0.1")
  (author "mbc")
  (copyright (2022))
  (synopsis "")
  (description "")
  (home-page "www.build-a-bot.biz")
  (license gpl3+)
  (dependencies `())
  (skip ())
  (files (libraries
           ((scheme-file "ebbot") (directory "ebbot" (scheme-file "twitter"))))
         (tests ((directory "tests" ())))
         (programs ((directory "scripts" ())))
         (documentation
           ((org-file "README")
            (symlink "README" "README.org")
            (text-file "HACKING")
            (text-file "COPYING")
            (directory "doc" ((texi-file "ebbot")))))
         (infrastructure
           ((scheme-file "guix")
            (text-file ".gitignore")
            (scheme-file "hall")))))
